services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hello
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    environment:
      POSTGRES_CONN_STRING: "postgres://admin:hello@database/tasks?sslmode=disable"
    depends_on:
      - database
    ports:
      - "8080:8080"
